### ISSUE TITLE
Timer spam when org file is opened by org-agenda

### ISSUE THREAD

**Issue by aavanian** [jdtsmith/org-modern-indent#11] opened 2023-12-21 15:09 UTC
I'm not 100% sure that's what's going on but it seems that if an org file is opened in a certain way (typically in the case I observe, by org-agenda), org-indent doesn't finish 'preparing' the buffer and adding it to `org-indent-agentized-buffers` (I suppose because the buffer hasn't been displayed yet) and so org-modern-indent's timer resets itself indefinitely until the buffer is interactively visited or some other condition that lead to org-indent adding the buffer to `org-indent-agentized-buffers`.

With a large amount of files in `org-agenda-files`, this slows down emacs since #number-of-buffer timers are executing every 0.1s. I'm not sure if there's a setting I could use to force org-indent to complete (from what I understand, `org-indent-agent-*-delay` wouldn't help since they skip the buffer if it's not active.

**Comment by jdtsmith** [comment] 2023-12-25 21:04
Thanks for the report.  I can confirm that `org-modern-indent--wait-and-refresh` simply arranges to have itself called again every 100ms until the buffer appears on `org-indent-agentized-buffers`.  Can you spell this out in more detail?  Are the buffer of interest actually being opened and viewed?  Maybe we need a more reliable hook from org-indent.

**Comment by jdtsmith** [comment] 2023-12-25 21:40
Please try my most recent commit and report back.  I reuse the timer (to prevent garbage buildup) and give up after 5 tries per buffer.  I don't know why org-indent starts but never finishes initializing in your buffers; probably the right thing is to prevent org(-modern)-indent from running in that context.

**Comment by jdtsmith** [comment] 2023-12-26 14:32
So it sounds like the max-5 fix helps but there are still slowdowns due to all the timers proliferating.  One thing I still don't understand: do you _want_ all 450 buffers fully org-(modern)-indent'ed? Or would you prefer org-indent to just leave those alone?  If you don't care to actually look at those buffer, the right thing to do is to disable org-indent and org-modern-indent when buffers are loaded in this manner via org-agenda, except if/when you actually display them in a window.  This is simlar to what, e.g., consult preview does.  Why spend time initializing buffers for display which you will never actually look at?

In terms of a more durable fix, since `org-modern-indent` uses the line-prefixes `org-indent` places there, it's pretty much captive to whatever setup cadence the latter implements.  It would be _really_ useful for `org-indent` to have an `org-indent-buffer-init-finished` abnormal hook (called with the buffer).  In fact, using advice or anything more invasive would be quite fragile and prone to breaking, given the convoluted design of the "agentized" delay initialization.   

There in fact is a perfect spot in org-indent to call such a hook:

```elisp
         ;; Job is complete: un-agentize buffer.
	 (unless interruptp
	   (setq org-indent-agentized-buffers
		 (delq buffer org-indent-agentized-buffers))
           (run-hook-with-args 'org-indent-buffer-init-finished buffer)) ;; <-- added
```

Do you want to engage the org mailing list folks to see about adding such an abnormal hook to `org-indent`?

**Comment by jdtsmith** [comment] 2023-12-26 17:35
Great.  If the org folks agree it's a trivial update.

**Comment by jdtsmith** [comment] 2023-12-31 19:22
Any traction on an `org-indent-finished` hook?

**Comment by jdtsmith** [comment] 2024-01-01 15:58
Great, thanks for pushing this along.  Please feel free to submit a patch.  You'd need to add a `defcustom` as well.  Once that is in we can try using it on a branch; should be effective and straightforward.  Then we'll need to decide how to handle version dependence.  One idea would be to use the hook if present, and stick with current timer approach otherwise.

**Comment by jdtsmith** [comment] 2024-01-03 23:33
Great, thanks for this.  Can you give the `org-buffer-init-hook` branch a try with (and without) this new version and let me know how it goes?

**Comment by jdtsmith** [comment] 2024-01-04 19:02
OK thanks.  Good point about leaving it active after init failure; pushed a fix; please give a try and see if that works well in your case. 

I don't know when org 9.7 will release (soon?), but given that your case is pretty rare I think the current setup is OK.

**Comment by jdtsmith** [comment] 2024-01-06 15:45
Great, thanks for bringing this to my attention.

**Closed by jdtsmith** 2024-01-06 15:45 UTC
