### ISSUE TITLE
Block indentation doesn't account for mixed-pitch-mode

### ISSUE THREAD

**Issue by Jake-Moss** [jdtsmith/org-modern-indent#14] opened 2024-03-08 09:46 UTC
Thanks for this package, it looks great, but block indentation fails when using mixed-pitch-mode on a block in  a list in a header.
![image](https://github.com/jdtsmith/org-modern-indent/assets/49361082/d075d045-bf6b-4229-b3d4-29c79214b766)

This doesn't occur when:
- Mixed pitch is disabled or,
- When plain variable pitch is used instead or,
- `org-modern-indent-mode` is disabled (i.e. `org-indent-mode` alone handles this correctly)
- The block is top level, in a list or not

It seems to be the combination of `mixed-pitch-mode`, `org-modern-indent`, and line wrapping with in a list in a header. I suspect something is grabbing the wrong face.

Here's the buffer in fundamental mode
![image](https://github.com/jdtsmith/org-modern-indent/assets/49361082/7dbdec97-1d43-4a56-90af-7a1ff30e3cd8)

And the actual text
```
#+begin_quote
This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text all in a single line
#+end_quote

- top level list
  #+begin_quote
  This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text all in a single line
  #+end_quote


* Header
#+begin_quote
This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text all in a single line
#+end_quote

** sub header but with lists
- list
  #+begin_quote
  This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text all in a single line
  #+end_quote
```

This is all using Overpass as my variable pitch font.
```lisp
(set-face-attribute 'variable-pitch nil :font "Overpass")
```

**Comment by Jake-Moss** [comment] 2024-03-08 10:36
It seems that this may also be theme related, this works with `variable-pitch-mode` and `doom-material` but not with  `modus-operandi`

**Comment by jdtsmith** [comment] 2024-03-09 22:55
To make progress you'll need to narrow this down.  Can you put together a reproducer from `emacs -Q`, loading only `org-modern-indent` and a short org file example?  

The other thing to look at is to go to the beginning of the mis-wrapped line, and `C-u C-x =`, then click on `wrap-prefix` and `line-prefix`.  The wrap prefix should look something like:

```elisp
#("             │" 13 14
  (face org-modern-indent-bracket-line))
```

**Comment by jdtsmith** [comment] 2024-03-09 23:24
OK I see one issue, the wrap for block-indented text does not have `org-indent` face applied.  I've pushed a fix up.  This _still_ will not work well if the "real" text indent you insert is in a variable pitch font, and org-indent is in a fixed pitch.    Not sure if `mixed-pitch-mode` will alleviate that for you.

**Comment by Jake-Moss** [comment] 2024-03-10 07:05
Here's a reproducible example
```lisp
(require 'package)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(use-package mixed-pitch
  :ensure t)

(use-package org-modern
  :ensure t)

(use-package compat
  :ensure t)

(use-package org-modern-indent
  :load-path "/home/jake/.emacs.d/testing/org-modern-indent"
  :config ; add late to hook
  (add-hook 'org-mode-hook #'org-modern-indent-mode 90))

(with-eval-after-load 'org (global-org-modern-mode))

(setq org-startup-indented t)

(add-hook 'org-mode-hook #'mixed-pitch-mode)
(global-visual-line-mode)

(switch-to-buffer "test.org")
(insert "#+begin_quote
This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text all in a single line
#+end_quote

- top level list
  #+begin_quote
  This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text all in a single line
  #+end_quote


* Header
#+begin_quote
This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text all in a single line
#+end_quote

** sub header but with lists
- list
  #+begin_quote
  This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text This is some long text all in a single line
  #+end_quote")
(org-mode)
```

It shows a wrap prefix of
```
#("     │" 5 6
  (face org-modern-indent-bracket-line))
```
and a line prefix of
```
#("    " 0 4
  (face org-indent))
```

Not sure where you pushed as I don't see any new commits on this repo. Happy to test any snippets you throw at me

**Comment by Jake-Moss** [comment] 2024-03-10 07:08
> I'm not familiar with `mixed-pitch-mode`, but it will not work to use variable pitch with org-indent in general, because both it (and org-modern-indent) rely on fixed number of spaces taking up a fixed amount of space. It appears a wrap-prefix in fixed-pitch does not preserve this property.

With that example you'll find that `variable-pitch-mode` does work with `org-modern-indent`, it works quite well actually, as well as plain `org-indent-mode`.
![image](https://github.com/jdtsmith/org-modern-indent/assets/49361082/43e5e30d-3dbe-4256-b180-33a3ce6baa06)

**Comment by jdtsmith** [comment] 2024-03-10 14:51
Sorry I had forgotten to push, it's there now (and should help but not necessarily solve it for mixed-pitch). 

The issue is org-indent uses (virtual display) spaces styled with the `org-indent` face to indent.  But org itself (or you) insert _real space_ in the buffer to start the indented block inside lists (presumably with the default space).  These space _must_ have the same width for alignment to be correct.

So please find out if this is true.  You can use the `C-u C-x =` to find out the face of any leading space, and within the wrap-prefix as well (which should now be `org-indent` face with my latest push).  If these faces are not from the same family (either fixed or not) you'll get misalignment like this.  Maybe this could be fixed by ensuring `org-indent` face has the same variable width font family as the normal `default` face. 

In any case, this config needs to happen with mixed-pitch mode and affects the bultin org-indent, so I recommend opening an issue there if it's not clear how to fix it.

**Closed by jdtsmith** 2024-03-10 14:51 UTC

**Comment by Jake-Moss** [comment] 2024-03-11 01:45
Thanks for your responses and pointing me in the right direction, I understand what you mean now. I also took the time to have crack at this myself and found a fix. I've put it up in #15 . It applies the `org-indent` face to only the number of virtual spaces instead of the virtual and real.
